### ISSUE TITLE
关于Mybatis 方法执行顺序的质疑

### ISSUE THREAD

**Issue by WhyWhatHow** [kailuncen/mybatis-cache-demo#1]
## 关于作者在[聊聊Mybatis缓存机制](https://tech.meituan.com/2018/01/19/mybatis-cache.html)中一级缓存执行流程的一些质疑

**Mybatis 是默认开启 cacheEnabled** =true , 也就是说,cachingExecutor 默认是执行的.

 我认为 [聊聊Mybatis缓存机制](https://tech.meituan.com/2018/01/19/mybatis-cache.html)文章在一级缓存执行流程解释说明时存在漏洞,会给读者(比如我)带来误解), 希望可以修改一下原文.
* Mybatis 忽略 CachingExecutor 的执行顺序: 
![image](https://user-images.githubusercontent.com/33270266/111412083-b58ed880-8716-11eb-8d24-15d327701730.png)
* Mybatis 方法真正执行顺序:
![image](https://user-images.githubusercontent.com/33270266/111412132-c93a3f00-8716-11eb-8eb8-282f5a54114a.png)

## 结论:

 mybatis  查询默认执行流程:

 **二级缓存 (CachingExecutor)-> 一级缓存(BaseExecutor.localCache) ->DB**  

[mybatis执行流程.pdf](https://github.com/kailuncen/mybatis-cache-demo/files/6153619/mybatis.pdf)

**Comment by GGGGGHT** [comment]
正解 mybatis会根据是否开启二级缓存(默认为开启 如果需关闭需要手动配置 ` <setting name="cacheEnabled" value="false"/>`)
当开启二级缓存时 则先去查询二级缓存  否则直接走一级缓存  最后执行sql 去查询数据库
